#pragma once

#include "Message.h"

static const RESPONSE_CODE ROUTER_RESPONSE_CODE_OK             = 1;
static const RESPONSE_CODE ROUTER_RESPONSE_CODE_PONG           = 2;
static const RESPONSE_CODE ROUTER_RESPONSE_CODE_REGISTERED     = 3;
static const RESPONSE_CODE ROUTER_RESPONSE_CODE_UNREGISTERED   = 4;
static const RESPONSE_CODE ROUTER_RESPONSE_CODE_FETCH_COMPLETE = 5;

static const RESPONSE_CODE ROUTER_RESPONSE_CODE_ERROR_SERVER_UNREACHABLE       = -1;
static const RESPONSE_CODE ROUTER_RESPONSE_CODE_ERROR_BAD_REQUEST              = -2;
static const RESPONSE_CODE ROUTER_RESPONSE_CODE_ERROR_UNAUTHORIZED             = -3;
static const RESPONSE_CODE ROUTER_RESPONSE_CODE_ERROR_DUPLICATE_IP_PORT        = -4;
static const RESPONSE_CODE ROUTER_RESPONSE_CODE_ERROR_REACHED_MAXIMUM_CAPACITY = -5;
static const RESPONSE_CODE ROUTER_RESPONSE_CODE_ERROR_NOT_REGISTERED           = -6;

static const REQUEST_CODE ROUTER_REQUEST_CODE_PING       = 1;
static const REQUEST_CODE ROUTER_REQUEST_CODE_REGISTER   = 2;
static const REQUEST_CODE ROUTER_REQUEST_CODE_UNREGISTER = 3;
static const REQUEST_CODE ROUTER_REQUEST_CODE_GET_NODES  = 4;

#define ROUTING_SERVER_IP   "127.0.0.1"
#define ROUTING_SERVER_PORT "9000"

#define MAX_ROUTING_SERVER_NODES 60

// TYPE OF RESPONSE + COUNT OF ITEMS + MAX SIZE OF ARRAY TO HOLD ALL NODES AT ONCE + 1 empty space between each item
#define MAX_SOCKET_BUFLEN (sizeof(RESPONSE_CODE) + sizeof(uint32_t) + MAX_ROUTING_SERVER_NODES * sizeof(NodeInfo) * 2)